# 公共仓库地址
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/MingYik/YikModul.git'
platform :ios, '11.0'
# 关闭全局警告
inhibit_all_warnings!

target "ObjectCDemo" do
    use_frameworks!
    # 布局依赖库
    pod 'Masonry'
    pod 'FuhaiRbox'
end


post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            #解决swift模块问题
            config.build_settings['SWIFT_VERSION'] = '5.0' 
            #解决platform模块问题
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
        end
    end
end

