# 公共仓库地址
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/MingYik/YikModul.git'
platform :ios, '11.0'
# pods转Modular可直接Swift中import不需bridging-header桥接
use_modular_headers!
# 关闭全局警告
inhibit_all_warnings!

target 'SwiftDemo' do
  # 布局依赖库
  pod 'SnapKit'
  pod 'FuhaiRbox'
end


post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            #解决swift模块问题
            config.build_settings['SWIFT_VERSION'] = '5.0' 
            #解决platform模块问题
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
        end
    end
end
